author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Component-Server-NNTP
no_index: 
  directory: 
    - inc
    - t
requires: 
  POE: 0.38
  POE::Component::Client::NNTP: 1.05
  POE::Component::Pluggable: 0
  Socket: 0
version: 0.95
